services:
  pix-db:
    image: postgres:15
    container_name: postgres
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pix-network

  pix-db-test:
    image: postgres:15
    container_name: postgres-test
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - "${HOST_DB_TEST_PORT}:5432"
    volumes:
      - db-data-test:/var/lib/postgresql/data
    networks:
      - pix-network

volumes:
  db-data:
  db-data-test:

networks:
  pix-network:
    driver: bridge